### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by sohate** [Marginal/QLVideo#104]
My version is not 2.0. There was a guide how to uninstall previous versions of the app. Now we have only two ways: drag the app to the trash and homebrew. I don't have the app in the application folder and I don't have homebrew. Can you tell me the terminal version of the uninstalling?

**Comment by sohate** [comment]
Found it in terminal.

**Comment by sohate** [comment]
sudo rm -rf "/Library/Application Support/QLVideo" "/Library/QuickLook/Video.qlgenerator" "/Library/Spotlight/Video.mdimporter"

**Comment by Marginal** [comment]
Added instructions here: https://github.com/Marginal/QLVideo/wiki/Uninstall
