### ISSUE TITLE
V 1.96, 1,95, 1.94: Crash with *.avi on Mac Mini 2012 with Catalina

### ISSUE THREAD

**Issue by renglm** [Marginal/QLVideo#105]
Reloading of thumbnails of all videos not working.
Apparently the minimal hardware is not sufficiently defined.
V 1.93 is working as it is described.
Only got hold on this because of the message of V2.00 app on hardware (late 2013).
1.96 crashed 'silently' (in reality brought down my Mac mini, search was complicated)

**Comment by Marginal** [comment]
v1.94 is the last version that supports Macs older than "late-2013" without AVX2 support.
More recent versions require a late-2013 or newer Mac, This is documented at https://github.com/Marginal/QLVideo/wiki/Getting-Started#limitations

**Comment by Marginal** [comment]
I've made [Release 1.99](https://github.com/Marginal/QLVideo/releases/tag/rel-199) with support for older hardware.
