### ISSUE TITLE
MKV files have no extended properties - solved!

### ISSUE THREAD

**Issue by ctismer** [Marginal/QLVideo#113]
Before moving to Monterey or now Ventura, some extra info about MKV files was listed, like duration, codec etc. This info seems to be completely gone, which again makes QLVideo less usable when working with video files. Can that be solved?
I would like to have the same info as on MP4 files.

Cheers -- Chris

**Comment by ctismer** [comment]
Update: The above reported problem only exists when I use an **external SSD or hard drive.** Internally on the system drive, all attributed are shown. I would love to know if this is an QLVideo problem at all. May be some obscure settings problem?
And as said, before Monterey everything worked.

**Comment by ctismer** [comment]
Hi friends, suddenly came the solution.
MKV properties are recorded also in external drives, but **you need the following**:
If you open the drive properties in Finder, by pressing Apple-I, there is a marker box at the very bottom of the info pane.
> Ignore Ownership

You need to **un-tick that marker box**.
It is possible that your name disappears now from `Sharing & Permissions`.
Please add your name and allow read and write.
Right to the `+ -` buttons there is a drop-down menu. Select `Apply to enclosed items`.

From now on, newly added MKV files have the additional info.

**Comment by Marginal** [comment]
Thanks. Documented this at https://github.com/Marginal/QLVideo/wiki/Troubleshooting#finder-doesnt-show-metadata-for-non-native-video-files
