### ISSUE TITLE
Why AVX2?

### ISSUE THREAD

**Issue by Fred-IV** [Marginal/QLVideo#115]
Why require AVX2?
Can't it be recompiled to not need it?
This is the first app I have run into that says it's required, but why?
Can it be fixed to run without it?
Maybe just a compiler switch?
If everyone else can get along without it, this simple, small program should be able to, and it shouldn't be that hard.

=-=-=-=-=-=-=-=-=-=-==-=-=-=

QuickLook Video requires a
late-2013 Mac or newer, with
AVX2 support
The QuickLook and Spotlight plugins
will crash!

**Comment by Marginal** [comment]
[Release 1.99](https://github.com/Marginal/QLVideo/releases/tag/rel-199) doesn't require AVX2. 
https://github.com/Marginal/QLVideo/wiki/Getting-Started#limitations
