### ISSUE TITLE
Please recompile for no AVX2!!!

### ISSUE THREAD

**Issue by Fred-IV** [Marginal/QLVideo#117]
"QuickLook Video requires a
late-2013 Mac or newer, with
AVX2 support
The QuickLook and Spotlight plugins
will crash!"

Why require AVX2?
PLEASE fix it! It should just be a simple compiler switch.

Many other companies have fixed their software, like World of Warcraft, and others.
When Blizzard missed this issue, they fixed it within hours.
I don't think it's a hard fix.
A few companies , like VMWare suck, and no longer work, because they refuse to, or don't have the skill, to fix it.
At least Parallels works fine.

Our older Macs are faster than most new Macs and PCs.
The ONLY issue is AVX2, and you can fix it at compile. There is no fix for us. It's not even a Mac issue, it's the Intel chips.

There's no way we are going to replace our perfectly good, and as I said, far faster systems, just for a few apps that are broken.
$12-50K for a new Mac, and with too many new problems.
None of the PCI slots work in the new 8,1's, and they can't even hold as much RAM.

Some day, as Intel is phased out, we will all go the way of the G5, or just use Windows 11 or Linux.

To be honest, I don't think I will ever own a M1, but if I ever do, it will be a cheap, used Mini, in addition to my Mac Pros.

Thanks

![cMP_Monterey](https://github.com/Marginal/QLVideo/assets/66499758/81ecdb53-41ac-4904-9394-f99b505a5145)

**Comment by Marginal** [comment]
https://github.com/Marginal/QLVideo/wiki/Troubleshooting#quicklook-video-requires-a-late-2013-mac-or-newer-with-avx2-support
