### ISSUE TITLE
Thumbnails not shown for MKV files

### ISSUE THREAD

**Issue by GreggHelt2** [Marginal/QLVideo#17]
I've downloaded and installed the latest release of QLVideo. 
Installed mostly to view thumbnails of MKV files in Finder. 
But thumbnails are not being shown for MKV files, just getting the default blank page icon. Verified that MKV files play in VLC and other apps. Relaunched Finder, rebooted machine several times, no luck.

As suggested in the README for issue reporting, here's sample output from glmanage debugging. Any thoughts?
PS Many thanks for any help!

****************************************************************************

qlmanage -p -d1 title00.mkv 
Testing Quick Look preview with files:
	title00.mkv
[DEBUG] Preview test for title00.mkv -- file:///Volumes/Visuals1/. Content type UTI: com.blurayplayersoftware.matroska
[DEBUG] Previewing file:///Volumes/Visuals1/title00.mkv. Content type UTI: com.blurayplayersoftware.matroska. Generator used: <QLGenerator Movie.qlgenerator>
[DEBUG] Loading <QLGenerator Movie.qlgenerator>
[DEBUG] Previewing file:///Volumes/Visuals1/title00.mkv finished
[DEBUG] Thumbnailing title00.mkv -- file:///Volumes/Visuals1/ - type: com.blurayplayersoftware.matroska - generator: <QLGenerator Movie.qlgenerator> (try #1)
[DEBUG] Thumbnailing file:///Volumes/Visuals1/title00.mkv. Content type UTI: com.blurayplayersoftware.matroska. Generator used: <QLGenerator Movie.qlgenerator>
[DEBUG] Thumbnailing file:///Volumes/Visuals1/title00.mkv did not produce anything
2015-01-16 14:44:14.519 qlmanage[1072:507] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9a27, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2015-01-16 14:44:14.520 qlmanage[1072:507] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9b4b, name = 'com.apple.CFPasteboardClient'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2015-01-16 14:44:14.521 qlmanage[1072:507] Failed to allocate communication port for com.apple.CFPasteboardClient; this is likely due to sandbox restrictions

*************************************************************************

And here's the full output from "qlmanage -m":

qlmanage -m
server: living for 424s (102 requests handled) - instant off: yes - arch: X86_64 - user id: 502
memory used: 1 MB (1347648 bytes) - used descriptors: 19/256
last burst: during 4.766s - 62 requests - 3.459s idle
plugins:
  org.videolan.avi -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.perian.nuppelvideo -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.iwork.keynote.sffkth -> /Library/QuickLook/iWork.qlgenerator (80)
  com.bittorrent.torrent -> /Applications/Transmission.app/Contents/Library/QuickLook/QuickLookPlugin.qlgenerator (1.0)
  org.khronos.collada.digital-asset-exchange -> /System/Library/QuickLook/SceneKit.qlgenerator (197.1)
  com.microsoft.powerpoint.pot -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.evernote.note-metadata2 -> /Applications/Evernote.app/Contents/Library/QuickLook/ENQuickLookGenerator.qlgenerator (1.0)
  org.perian.ogv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.videolan.wmv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.videolan.ogg-video -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.massanti.mediainfomac.flash-video -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  io.mpv.divx -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  public.audio -> /System/Library/QuickLook/Audio.qlgenerator (622.7)
  com.apple.iwork.pages.sfftemplate -> /Library/QuickLook/iWork.qlgenerator (80)
  org.xiph.ogv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.macblurayplayer.nuppelvideo -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  public.flc-animation -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.smpte.gxf -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.videolan.asf -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.adobe.illustrator.ai-image -> /System/Library/QuickLook/EPS.qlgenerator (622.7)
  io.mpv.rmvb -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  public.plain-text -> /System/Library/QuickLook/Text.qlgenerator (622.7)
  public.x509-printable-encoded-archive -> /System/Library/QuickLook/Security.qlgenerator (55047)
  public.movie -> /System/Library/QuickLook/Movie.qlgenerator (622.7 - loaded)
  com.real.realvideo -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.lov.coge.fxchain -> /Applications/CoGe/CoGe.app/Contents/Library/QuickLook/CoGeQuickLook.qlgenerator (1.0)
  com.omnigroup.omnigraffle.graffle-package -> /Applications/OmniGraffle Professional 5.app/Contents/Library/QuickLook/OmniGraffle.qlgenerator (3.0)
  com.apple.iwork.keynote.key -> /Library/QuickLook/iWork.qlgenerator (80)
  com.apple.ical.bookmark -> /System/Library/QuickLook/iCal.qlgenerator (622.7)
  org.niltsh.mplayerx-xvid -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.rsa.pkcs-12 -> /System/Library/QuickLook/Security.qlgenerator (55047)
  com.apple.keychain -> /System/Library/QuickLook/Security.qlgenerator (55047)
  public.mpeg-4 -> /System/Library/QuickLook/Movie.qlgenerator (622.7 - loaded)
  public.dv-movie -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  public.avi -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.videolan.mxf -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.videolan.realmedia -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.videolan.mkv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.iwork.numbers.sffnumbers -> /Library/QuickLook/iWork.qlgenerator (80)
  com.apple.notes.externalrecord -> /System/Library/QuickLook/Notes.qlgenerator (284)
  org.openxmlformats.spreadsheetml.sheet -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.real.realmedia-vbr -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.ibooksauthor.book -> /Library/QuickLook/iBooksAuthor.qlgenerator (1.0)
  org.videolan.rec -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  public.x509-certificate -> /System/Library/QuickLook/Security.qlgenerator (55047)
  com.apple.ichat.ichat -> /System/Library/QuickLook/iChat.qlgenerator (4226)
  com.apple.iwork.numbers.numbers-tef -> /Library/QuickLook/iWork.qlgenerator (80)
  com.omnigroup.omnigraffle.gstencil -> /Applications/OmniGraffle Professional 5.app/Contents/Library/QuickLook/OmniGraffle.qlgenerator (3.0)
  com.apple.localized-pdf-bundle -> /System/Library/QuickLook/LocPDF.qlgenerator (622.7)
  com.lov.veze-r.project -> /Applications/Vezér/Vezér.app/Contents/Library/QuickLook/VezerQuicklook.qlgenerator (1.0)
  com.adobe.encapsulated-postscript -> /System/Library/QuickLook/EPS.qlgenerator (622.7)
  com.apple.mail.emlx -> /System/Library/QuickLook/Mail.qlgenerator (1878.6)
  com.apple.ical.bookmark.todo -> /System/Library/QuickLook/iCal.qlgenerator (622.7)
  org.videolan.nsv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.ical.ics.event -> /System/Library/QuickLook/iCal.qlgenerator (622.7)
  public.xhtml -> /System/Library/QuickLook/Web.qlgenerator (622.7)
  org.niltsh.mplayerx-flash-video -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  io.mpv.ogv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.property-list -> /System/Library/QuickLook/Text.qlgenerator (622.7)
  com.microsoft.excel.xlt -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.iwork.keynote.sffkey -> /Library/QuickLook/iWork.qlgenerator (80)
  com.apple.iconset -> /System/Library/QuickLook/Icon.qlgenerator (622.7)
  com.lov.coge.mediabank -> /Applications/CoGe/CoGe.app/Contents/Library/QuickLook/CoGeQuickLook.qlgenerator (1.0)
  com.microsoft.wtv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.videolan.nuv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.openxmlformats.spreadsheetml.template -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.pict -> /System/Library/QuickLook/Clippings.qlgenerator (622.7)
  public.vcard -> /System/Library/QuickLook/Contact.qlgenerator (622.7)
  com.adobe.pdf -> /System/Library/QuickLook/PDF.qlgenerator (622.7)
  org.perian.flash-video -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.google.webm -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.videolan.tod -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.niltsh.mplayerx-mxf -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  io.mpv.flv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.videolan.flash -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  public.rtf -> /System/Library/QuickLook/Text.qlgenerator (622.7)
  com.apple.iwork.pages.pages-tef -> /Library/QuickLook/iWork.qlgenerator (80)
  com.apple.package -> /System/Library/QuickLook/Package.qlgenerator (622.7)
  com.microsoft.windows-media-wmv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.microsoft.word.stationery -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.iwork.pages.sffpages -> /Library/QuickLook/iWork.qlgenerator (80)
  com.microsoft.xesc -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.iwork.keynote.key-tef -> /Library/QuickLook/iWork.qlgenerator (80)
  org.openxmlformats.presentationml.slideshow -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.garageband.template.magic -> /Applications/GarageBand.app/Contents/Library/QuickLook/GBQLGenerator.qlgenerator (428.5)
  com.apple.addressbook.person -> /System/Library/QuickLook/Contact.qlgenerator (622.7)
  org.matroska.mkv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.iwork.numbers.sfftemplate -> /Library/QuickLook/iWork.qlgenerator (80)
  org.openxmlformats.presentationml.presentation.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.webarchive -> /System/Library/QuickLook/Web.qlgenerator (622.7)
  com.lov.coge.preset -> /Applications/CoGe/CoGe.app/Contents/Library/QuickLook/CoGeQuickLook.qlgenerator (1.0)
  io.mpv.mkv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.massanti.mediainfomac.matroska -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.safari.history -> /System/Library/QuickLook/Bookmark.qlgenerator (622.7)
  org.niltsh.mplayerx-divx -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  io.mpv.dv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.garageband.template.magicmentor -> /Applications/GarageBand.app/Contents/Library/QuickLook/GBQLGenerator.qlgenerator (428.5)
  com.apple.keynote.key -> /Library/QuickLook/iWork.qlgenerator (80)
  public.comma-separated-values-text -> /System/Library/QuickLook/Office.qlgenerator (32)
  org.openxmlformats.wordprocessingml.template.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.lov.coge.project -> /Applications/CoGe/CoGe.app/Contents/Library/QuickLook/CoGeQuickLook.qlgenerator (1.0)
  org.videolan.axv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.systempreference.prefpane -> /System/Library/QuickLook/StandardBundles.qlgenerator (622.7)
  org.niltsh.mplayerx-dv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.ichat.transcript -> /System/Library/QuickLook/iChat.qlgenerator (4226)
  com.apple.addressbook.group -> /System/Library/QuickLook/Contact.qlgenerator (622.7)
  io.mpv.avi -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.openxmlformats.wordprocessingml.document -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.omnigroup.omnigraffle.gstencil-package -> /Applications/OmniGraffle Professional 5.app/Contents/Library/QuickLook/OmniGraffle.qlgenerator (3.0)
  com.apple.iwork.pages.pages -> /Library/QuickLook/iWork.qlgenerator (80)
  org.smpte.mxf -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.iwork.keynote.kth -> /Library/QuickLook/iWork.qlgenerator (80)
  org.openxmlformats.wordprocessingml.template -> /System/Library/QuickLook/Office.qlgenerator (32)
  org.videolan.xesc -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.internet-location -> /System/Library/QuickLook/Clippings.qlgenerator (622.7)
  com.apple.iwork.numbers.numbers -> /Library/QuickLook/iWork.qlgenerator (80)
  com.divx.divx -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.massanti.mediainfomac.nuppelvideo -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.videolan.wtv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.ical.ics -> /System/Library/QuickLook/iCal.qlgenerator (622.7)
  org.openxmlformats.presentationml.template.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  org.videolan.3gp -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.quicktime-movie -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.omnigroup.omnigraffle.graffle -> /Applications/OmniGraffle Professional 5.app/Contents/Library/QuickLook/OmniGraffle.qlgenerator (3.0)
  indy.jt.niceplayer.mkv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.videolan.dv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  public.image -> /System/Library/QuickLook/Image.qlgenerator (622.7)
  com.apple.mail.email -> /System/Library/QuickLook/Mail.qlgenerator (1878.6)
  org.openxmlformats.presentationml.slideshow.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.iwork.numbers.template -> /Library/QuickLook/iWork.qlgenerator (80)
  com.microsoft.word.doc -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.ical.ics.todo -> /System/Library/QuickLook/iCal.qlgenerator (622.7)
  com.apple.safari.bookmark -> /System/Library/QuickLook/Bookmark.qlgenerator (622.7)
  indy.jt.niceplayer.divx -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.microsoft.powerpoint.ppt -> /System/Library/QuickLook/Office.qlgenerator (32)
  org.niltsh.mplayerx-ogg-video -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.lov.coge.clipsynth -> /Applications/CoGe/CoGe.app/Contents/Library/QuickLook/CoGeQuickLook.qlgenerator (1.0)
  org.perian.divx -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.microsoft.advanced-systems-format -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.finder.pictclipping -> /System/Library/QuickLook/Clippings.qlgenerator (622.7)
  org.videolan.divx -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  public.font -> /System/Library/QuickLook/Font.qlgenerator (622.7)
  org.oasis-open.opendocument.text -> /System/Library/QuickLook/Text.qlgenerator (622.7)
  public.html -> /System/Library/QuickLook/Web.qlgenerator (622.7)
  org.openxmlformats.presentationml.presentation -> /System/Library/QuickLook/Office.qlgenerator (32)
  public.xml -> /System/Library/QuickLook/Text.qlgenerator (622.7)
  org.webmproject.webm -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.openxmlformats.spreadsheetml.sheet.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.massanti.mediainfomac.ogv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.openxmlformats.spreadsheetml.template.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  org.niltsh.mplayerx-matroska-video -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.niltsh.mplayerx-rmvb -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.application -> /System/Library/QuickLook/StandardBundles.qlgenerator (622.7)
  org.openxmlformats.presentationml.template -> /System/Library/QuickLook/Office.qlgenerator (32)
  io.mpv.xvid -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.rtfd -> /System/Library/QuickLook/Text.qlgenerator (622.7)
  com.microsoft.powerpoint.pps -> /System/Library/QuickLook/Office.qlgenerator (32)
  org.mythtv.nuppelvideo -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.microsoft.excel.xls -> /System/Library/QuickLook/Office.qlgenerator (32)
  public.svg-image -> /System/Library/QuickLook/Web.qlgenerator (622.7)
  org.perian.matroska -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.adobe.flash.video -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.videolan.gxf -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.videolan.vro -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.macblurayplayer.matroska -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.openxmlformats.wordprocessingml.document.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.real.realmedia -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  org.videolan.quicktime -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.macblurayplayer.divx -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.apple.finder.textclipping -> /System/Library/QuickLook/Clippings.qlgenerator (622.7)
  com.microsoft.word.dot -> /System/Library/QuickLook/Office.qlgenerator (32)
  com.apple.iwork.pages.template -> /Library/QuickLook/iWork.qlgenerator (80)
  com.apple.garageband.project -> /Applications/GarageBand.app/Contents/Library/QuickLook/GBQLGenerator.qlgenerator (428.5)
  org.videolan.webm -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  io.mpv.wmv -> /Library/QuickLook/Video.qlgenerator (1.7.3)
  com.blurayplayersoftware.matroska -> /System/Library/QuickLook/Movie.qlgenerator (622.7 - loaded)
  com.macblurayplayer.ogv -> /Library/QuickLook/Video.qlgenerator (1.7.3)

**Comment by GreggHelt2** [comment]
PS This is on OSX 10.9.5 (Mavericks)

**Comment by Marginal** [comment]
Should be fixed in Release 1.80.

**Comment by GreggHelt2** [comment]
Thanks for such a quick turnaround with a fix!
QLVideo 1.80 now works great for me with MKV files etc.
