### ISSUE TITLE
Exclude .mp4 thumbs?

### ISSUE THREAD

**Issue by willhowe** [Marginal/QLVideo#19]
Great work guys, everything works smooth. It would be great if QLVideo had the option/feature of not effecting .mp4 file icons, as this was the only thumb OS handled well, and now with QLVideo running the film covers get unsightly black borders left & right. Screenshot: http://willhow.es/14E2g

**Comment by Marginal** [comment]
Fixed in Release 1.83.

**Comment by willhowe** [comment]
Tested & working great, Kudos on the instant implementation, Great work!
