### ISSUE TITLE
Where is the cache stored?  Also, encrypted DMG issue

### ISSUE THREAD

**Issue by gitguys** [Marginal/QLVideo#20]
Thank you for your work on QLVideo.

I was curious about a potential security issue of where the images are stored?  I know Quick Look has a cache, does QLVideo store in the same place and/or elsewhere?

Also, are the images stored in a cache if one uses an encrypted DMG?  From what I understand, Quick Look does not keep anything stored in cache when using Quick Look on items within a DMG.  Is this the same case QLVideo?

**Comment by Marginal** [comment]
The way that the QuickLook architecture works is that the system quicklookd process invokes a "generator" plugin to produce an image of a file at a certain resolution. QLVideo is one such "generator" - others live in /System/Library/QuickLook and /Library/QuickLook.

The "generator" plugins are sandboxed so by default they only have access to their own plugin bundle and to the requested file. The "generator" plugins do not and cannot interact directly with the cache - they merely return an image back to the quicklookd process. The quicklookd process stores these images in its cache, which is a per-user sqlite database on the system disk and is described [here](http://encase-forensic-blog.guidancesoftware.com/2014/05/examination-of-mac-os-x-quick-look.html).

You can examine the contents of this cache with the [sqlite3](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/sqlite3.1.html) command or with any sqlite database browser app. You can empty the cache with the command `qlmanage -r cache` .

> are the images stored in a cache if one uses an encrypted DMG? From what I understand, Quick Look does not keep anything stored in cache when using Quick Look on items within a DMG

I believe (but I haven't checked) that quicklookd's cache *does* contain images from files on encrypted volumes.

**Comment by gitguys** [comment]
Thank you for your detailed explaination.

**Comment by Marginal** [comment]
> Is there a terminal command to 'secure delete' the cache?

Not easily. If you routinely have files on disk containing credentials that you would like to secure then you should probably enable FileVault on your system disk.

**Comment by gitguys** [comment]
When I type...

qlmanage -r cache

...into terminal in Mavericks it shows a bunch of instructions for qlmanage afterwards.  Is that normal behavior or am I doing something incorrectly to clear the cache.  I would normally only expect all that info if I was doing -m

**Comment by Marginal** [comment]
You have a typo.

**Comment by gitguys** [comment]
I was copying and pasting it.  Must have been an issue with system maintenance.  Once the monthly cron job went through it started working properly and now it says...

qlmanage: call reset on cache

...which seems more like what I'd expect.  Thank you for assisting me with this and thank you again for your work on QLVideo.
