### ISSUE TITLE
Game changer with libVLC on Mac?

### ISSUE THREAD

**Issue by gitguys** [Marginal/QLVideo#21]
Could this be implemented in some way to view all the VLC compatible video formats in Quick Look?

Or, if that's simply not possible, could an app be made to behave similar to Quick Look with libVLC?  

For example, instead of triggering Quick Look, a different shortcut could trigger the video to open in a similar window via an app or process that's always running and exhibits the same behavior as Quick Look (or even better)?  This would be incredible and I'm sure plenty of people aside from people who work with video would buy or donate for it.  I know I would.

http://www.videolan.org/vlc/libvlc.html

**EDIT** -  I hunted around and see that you're already using libVLC I think, but it won't work with Quick Look for video.  Could that change in the future with libVLC updates they're making today?  Or, do you think my app idea may be the only alternative?

**Comment by Marginal** [comment]
> could an app be made to behave similar to Quick Look with libVLC?

If you want to launch a video player app on the selected file in Finder using a keyboard shortcut then use ⌘-↓ .

But a key feature of QuickLook is that the user's navigation in the Finder window is tracked and the contents of the preview window is kept updated to reflect the user's selection. I don't know of any way to emulate this behaviour with a "fake" previewer app.

libvlc can't help with this.
