### ISSUE TITLE
Retina iMac Problem

### ISSUE THREAD

**Issue by daegalja** [Marginal/QLVideo#22]
Please see the attached files.
I'm only guessing this is a retina iMac issue,
because none of my other macs showing this symptom.

It works fine until I place it in the dock area.
What seems to be the issue here?

Thank you so much for the great work. :)
DK

![screen shot 2015-03-21 at 3 35 36 am](https://cloud.githubusercontent.com/assets/11576845/6758451/992e24d8-cf7b-11e4-8852-5dcb00553e36.png)
![screen shot 2015-03-21 at 3 31 55 am](https://cloud.githubusercontent.com/assets/11576845/6758452/996d6fa8-cf7b-11e4-932b-b0419b2c7f18.png)

**Comment by Marginal** [comment]
Thanks for the report. I haven't seen this in my (limited) testing on Retina machines. Could you explain what you mean by "It works fine until I place it in the dock area" ?

**Comment by Marginal** [comment]
Should be fixed in Release 1.84.

**Comment by daegalja** [comment]
Thank you so much. :)

DK
