### ISSUE TITLE
Add this to brew?

### ISSUE THREAD

**Issue by OmgImAlexis** [Marginal/QLVideo#28]
Any chance this could be added to brew to allow easier installation?

**Comment by Marginal** [comment]
It's available as a Homebrew [Cask](http://caskroom.io/):
```brew cask install qlvideo```

And I'm sure the Homebrew project would welcome a patch to build from source.

**Comment by OmgImAlexis** [comment]
Completely forgot about cask, would you mind adding a link to the brew package for qlvideo to the `README.md`?

**Comment by Marginal** [comment]
Done.
