### ISSUE TITLE
Can't preview H.265 video in .mp4 files

### ISSUE THREAD

**Issue by 1davi** [Marginal/QLVideo#29]
I converted some videos using HandBrake and the thumbnails show up on Finder, but they don't appear in the "Get Info" window and on Quick Look.

**Comment by Marginal** [comment]
There weren't very many H.265 samples around when I was testing H.265 support, so it's possible that I've missed something. 

Please mail me at github AT marginal.org.uk with a link to one of your files. (If it's easier for you, just make a small 10 second clip - so long as it still demonstrates the problem).

**Comment by Marginal** [comment]
Thanks - it's a "hevc" (Main) encoded video inside a "mp42" container, with a .MP4 filename extension. What appears to be happening on my machine (Yosemite) is that QuickLook thinks it can handle the file itself using AVFoundation so isn't handing the file off to this plugin. AVFoundation can't handle H.265 files, so we have a failure.

@1davi As a workaround, try telling Handbrake to use the .M4V extension. (I know this suggestion sounds silly, but QuickLook really does seem to treat files with .MP4 and .M4V extensions differently). 

Meanwhile I'll see if I can identify a proper fix.

**Comment by 1davi** [comment]
You're right, using .m4v instead of .mp4 seems to fix the problem.

Renaming the extension of the file to .m4v works too, do you think this can cause any problem?


________________________________
De: Jonathan Harris <notifications@github.com>
Enviado: domingo, 13 de dezembro de 2015 03:33
Para: Marginal/QLVideo
Cc: 1davi
Assunto: Re: [QLVideo] HEVC/H.265 Thumbnails (#29)


Thanks - it's a "hevc" (Main) encoded video inside a "mp42" container, with a .MP4 filename extension. What appears to be happening on my machine (Yosemite) is that QuickLook thinks it can handle the file itself using AVFoundation so isn't handing the file off to this plugin. AVFoundation can't handle H.265 files, so we have a failure.

@1davi<https://github.com/1davi> As a workaround, try telling Handbrake to use the .M4V extension. (I know this suggestion sounds silly, but QuickLook really does seem to treat files with .MP4 and .M4V extensions differently).

[https://avatars0.githubusercontent.com/u/14959546?v=3&s=400]<https://github.com/1davi>

1davi<https://github.com/1davi>
github.com
Follow 1davi on GitHub and watch them build beautiful projects.


Meanwhile I'll see if I can identify a proper fix.

-

**Comment by Marginal** [comment]
> Renaming the extension of the file to .m4v works too, do you think this can cause any problem?

Won't cause any problems - it just causes OSX to bypass some attempted optimizations that it tries (and in this case fails) to do for public.mpeg-4 files, that it doesn't try to do for com.apple.m4v-video files.

**Comment by Marginal** [comment]
QuickLook's behaviour with H.265 .mp4 files is broken in different ways on Yosemite and El Capitan. I can't work around this in this plugin, so I've added a note to the [Limitations](https://github.com/Marginal/QLVideo/wiki/Getting-Started#limitations) section of the documentation.

**Comment by Marginal** [comment]
Note: This appears fixed in the Sierra beta.

**Comment by Gahamelas** [comment]
Here in Catalina not being a able to see preview in Finder using either mp4 or renaming the files to m4v. Any ideas?
