### ISSUE TITLE
.PSD cropped thumbnails

### ISSUE THREAD

**Issue by willhowe** [Marginal/QLVideo#31]
On OS X El Capitan 10.11.3, QLVideo is cropping the thumbnails of very large (pixel dimension) Adobe Photoshop .psd files, they flash in to view correctly but then seem to get cropped 16:9 on white canvas.

**Comment by Marginal** [comment]
.psd files are handled by Apple's built-in "Image" QuickLook plugin, not by QLVideo.

**Comment by willhowe** [comment]
Apologies Marginal, it seemed to resolve when I uninstalled QL so I assumed it was that, must have been a coincidence - keep up the good work!
