### ISSUE TITLE
Show Error Preview If Generation Failed

### ISSUE THREAD

**Issue by acuntex** [Marginal/QLVideo#42]
Hi,

is there any way QLVideo could show some Placeholder Image as Preview if it wasn't able to create a preview instead of the default Finder image?

I'm always wondering if it failed or if I still have to wait for some preview image.

Thanks!

**Comment by Marginal** [comment]
Could do, but I'm not sure why a placeholder image would be better than your media player app's icon.

The polite thing for a plugin to do is the current behaviour - say that it can't generate a preview/thumbnail so that QuickLook can hand off to another plugin if there is one.

**Comment by acuntex** [comment]
Unfortunately Quicklook does not handle it by another plugin.. e.g. the default one which in some cases would generate thumbs but QLVideos doesn't.
Sometimes it takes time to generate the thumb and when you browse through folders you are not sure: Is he not able to do it or does it hang?

qlmanage -r helps the plugin to continue and then some videos get a thumb, some don't.

I miss the old time when Perian worked :(

**Comment by acuntex** [comment]
One more thing: I saw that in Snapshotter.m e.g. are a lot of "return nil".

Would it be possible to log on a certain loglevel like -d2 why the plugin wasn't able to generate a thumbnail?

**Comment by Marginal** [comment]
Closing as won't (actually can't) fix.
Unfortunately this app can't know whether another plugin might be able to produce a thumbnail or preview. It would be rude to return a placeholder image when another plugin (perhaps one of Apple's builtin plugins) might be able to.
