### ISSUE TITLE
Play 180/360-degree videos

### ISSUE THREAD

**Issue by Henrietta1989** [Marginal/QLVideo#44]
Please add support for 180/360-degree videos.

Just play that video file no matter what kind it is, for instance two spheres top of each other.

Since VLC and IINA (based on mpv) can play it, it's should be easy to see video playing in Quick Look too.

**Comment by Marginal** [comment]
Please post some links to some sample files and I'll have a look.

**Comment by Henrietta1989** [comment]
Sample Videos:

[http://www.samsung.com/global/galaxy/gallery/gear-360/](url)

**Comment by Marginal** [comment]
These .mp4 files are rendered in QuickLook by Apple's AVFoundation framework, which doesn't understand 360º videos. So you get something like:
![screen shot 2017-08-13 at 10 04 42](https://user-images.githubusercontent.com/1374740/29248389-f03ab55c-800e-11e7-9eb3-90d2f8b683d9.png)

This plugin can't fix that.
