### ISSUE TITLE
Set videos to "Mute" on default

### ISSUE THREAD

**Issue by gitgetgot** [Marginal/QLVideo#45]
Hi, 
is it possible to set up QLVideo to preview/play all the videos muted?

Maybe a setting via Defaults Write, or on a Preferences page?

(This sound a bit odd, but sometimes the user (me) is listening to music and just want to re*view* some videos with this fine program!)

(Big thank you for your work!!! Its makes fun again to browse my videos via finder!)

EDIT: hmm.. trying again to quickview some videos, it did not work anymore. Just thumbnails are shown (as written in the very long discussion here...). I'm pretty sure I previewed MKVs before....

**Comment by Marginal** [comment]
QLVideo provides static snapshots of fils that can't otherwise be previewed by QuickLook.
If you're seeing a moving preview then this is provided by macOS's built-in QuickLook implementation and so is out of the control of this plugin.
