### ISSUE TITLE
Metadata doesn't appear to be working on 10.13

### ISSUE THREAD

**Issue by BarryMode** [Marginal/QLVideo#46]
I've been using this for a while, and it's awesome, but just thought I'd report that it appears to not be compatible with the latest OS update. I tried reinstalling the cask but it didn't seem to change anything. If I'm wrong, sorry for the report. I don't see any codec information in the info window though. Not dimensions either or anything else.

I'm using the new encrypted APFS.

This is confirmed to be an issue after doing `brew cask reinstall qlvideo`

**Comment by gnucian** [comment]
I'm experiencing the same issue on 10.13.

**Comment by iiiGerardoiii** [comment]
Works fine here. I'm running 10.13 (17A365).
The image doesn't take the whole QuickLook window though, but at least the thumbnail is present.
![captura de pantalla 2017-09-28 a la s 12 15 23](https://user-images.githubusercontent.com/6264194/30980533-05bfe404-a447-11e7-9b2b-d8e8d05dbe9e.png)
![captura de pantalla 2017-09-28 a la s 12 10 49](https://user-images.githubusercontent.com/6264194/30980536-08d94338-a447-11e7-84e6-5995e10402cd.png)

**Comment by BarryMode** [comment]
@iiiGerardoiii I'm not referring to a thumbnail, I'm referring to the codec data. It's missing from the info window. It's also absent from the codec field in Finder. Here's an example of that.
<img width="214" alt="screen shot 2017-09-28 at 12 29 20 pm" src="https://user-images.githubusercontent.com/5648875/30981089-d8b16daa-a448-11e7-9e7d-d3abd3d3c989.png">

**Comment by MaddTheSane** [comment]
Part of that is that QuickLook plug-ins don't fill out metadata, that would need a Spotlight plug-in. I do have a [Spotlight plug-in](https://github.com/MaddTheSane/MKVImport) that should work.

**Comment by iiiGerardoiii** [comment]
@BarryMode true, I don't see a codec field in Finder. I see "codecs" in the info window though.
![captura de pantalla 2017-09-28 a la s 12 43 41](https://user-images.githubusercontent.com/6264194/30982118-1bca72dc-a44c-11e7-97fd-343ae445f2ab.png)

**Comment by MaddTheSane** [comment]
My bad, I thought this package only had a QuickLook plug-in, and not a metadata plug-in.

**Comment by BarryMode** [comment]
I hadn't checked a webm file, but for mkv and mp4 I've got nothing showing.

**Comment by gnucian** [comment]
My issue is different. I can see the codec info in Finder for HEVC videos in mp4 and mkv formats, but Finder no more shows the QuickLook previews for them. I could see them in 10.12. H.264 videos in mp4 format have no problem.

**Comment by BarryMode** [comment]
It's working now for me, so I'm going to close this since I opened it.
