### ISSUE TITLE
No previews in search/smart folders

### ISSUE THREAD

**Issue by Immateria** [Marginal/QLVideo#49]
I am unsure whether or not this is by design, but while the files I am referring to(a bunch of .mkv) have previews if I navigate to their directory, they do not have previews in a search or in my smart folders.

Mac mini 2012 i5/4GB on 10.13 High Sierra

**Comment by Marginal** [comment]
I sometimes see this. Looks like a Finder issue since this plugin isn't called to render the missing icon.

**Comment by Kagami** [comment]
I have a slightly different issue: thumbnails in Finder search are (mostly) fine but I don't have thumbnails in the quick Spotlight search (the one which you open with Cmd+Space/F4). But metadata (duration) is displayed correctly and I can even see the full thumbnail if I press Space. See screenshot.

What I've tried:
- `mdimport -r "/Applications/QuickLook Video.app/Contents/Library/Spotlight/Video.mdimporter"`
- `mdimport -i /path/to/folder`
- `killall -9 com.apple.quicklook.ThumbnailsAgent`
- Re-enabling Quick Look extension
- Re-index all Spotlight database
- Reboot

Some commands help to unstuck thumbnailer and it fixes missing thumbnails in Finder, but not in quick Spotlight search.
Any ideas?

<img src="https://github.com/Marginal/QLVideo/assets/533383/9efeae5e-6c43-4bb4-b5f1-76cc7a6a2aca" width="30%">

**Comment by Marginal** [comment]
Will be fixed in the next release.
