### ISSUE TITLE
Missing details in "More Info" in finder information window

### ISSUE THREAD

**Issue by Ribero** [Marginal/QLVideo#51]
<img width="377" alt="finder_info" src="https://user-images.githubusercontent.com/2266264/34101394-e8362fb8-e3e5-11e7-9ae6-ceb71d8438a0.png">

Finder "Info" does not give any additional information (see red rectangle in screenshot) if the file is stored on a network volume (see blue rectangle in screenshot).

No issues for files stored on a local drive.

My configuration : macOS High Sierra 10.13.2, Synology NAS (smb share), QLVideo 1.90

**Comment by Marginal** [comment]
You need to have Spotlight indexing enabled for Finder to obtain and display this info. You can check the status of the indexing by typing in the terminal app:
```mdutil -sv /Volumes/Films```
And enable indexing if disabled with:
```mdutil -i on /Volumes/Films```

If your server supports Apple Filing Protocol (AFP) or Netatalk you should use this in preference to SMB for Mac clients.

**Comment by Ribero** [comment]
Confirmed. It works (in SMB in my context).

Additional information : For people using a Synology NAS to store Videos, you must disable "Universal Search" and then use "mdutil -i on /Volumes/Folder_Name" to make it work. Universal Search is supposed to be compatible with Spotlight but...
