### ISSUE TITLE
Cannot delete "empty" folders from network share.

### ISSUE THREAD

**Issue by darkfader** [Marginal/QLVideo#52]
Does the thumbnails data ".@__thumb" not get cleaned up when (re)moving video files? I see these files on my NAS but not under macOS (via smb). So I can only remove them from my NAS. (QNAP)
`find . -name ".@__thumb" | while read f; do rm -rf "$f"; done`

**Comment by Marginal** [comment]
`.@__thumb` files are created by your QNAP NAS, and not by this plugin. They're used to display thumbnails in File Station and Media Station, and are not required or used by macOS's Finder.

You can disable them by setting "Scan Settings" to "Manual Scan" under Control Panel -> Applications -> Multimedia Management -> Media library.

**Comment by darkfader** [comment]
Oh dang. Stupid QNAP. My ReadyNAS software-wise was better xD
Anyway, I already seemed to have put it on manual but that didn't delete them automatically.

My good old slow ReadyNAS doesn't like too much indexing, SMBD was pretty much eating all CPU time after opening in the Finder and kept going even after closing the Finder window. I guess I should stop using it.
