### ISSUE TITLE
Video not playable in quicklook

### ISSUE THREAD

**Issue by goodman-capu** [Marginal/QLVideo#57]
For .mp4 or .mov files, without QLVideo installed, they can be directly played without opening. However, after installing, it only shows a thumbnail and the file is not playable (unless use space to quicklook).
Before installing QLVideo:
<img width="98" alt="before" src="https://user-images.githubusercontent.com/8862302/43043836-b3b0cd2a-8d4f-11e8-9091-cb4a00c8fee8.png">
After installing QLVideo:
<img width="106" alt="after" src="https://user-images.githubusercontent.com/8862302/43043838-b6b28bda-8d4f-11e8-927f-f2380c76c929.png">

**Comment by Marginal** [comment]
This is a side-effect of this plugin "owning" generation of thumbnails for video files. I don't know of an easy way around this.

**Comment by goodman-capu** [comment]
I think a easy way to solve this is to restrict file types it monitors.
For example, only generate thumbnail for .mkv and .avi files, and ignore .mp4 .mov files.

**Comment by goodman-capu** [comment]
Another way to think of it is like: If macOS can preview this item, then skip QLVideo.
I've never made a QuickLook Plugin before so I don't know whether it's possible.
