### ISSUE TITLE
_clampImageAlphaTo01 & _updateContentForLayerUsingIOSurface error and no playable preview for some video files

### ISSUE THREAD

**Issue by gkertai** [Marginal/QLVideo#60]
Certain video files only show a static image preview. For these videos the diagnostic log includes the following error:
```
$ qlmanage -p -d1 BigBuckBunny_2000hevc.mp4 
[DEBUG] Preview test for BigBuckBunny_2000hevc.mp4 -- file:///Volumes/…/. Content type UTI: public.mpeg-4
[DEBUG] Previewing file:///Volumes/…/BigBuckBunny_2000hevc.mp4. Content type UTI: public.mpeg-4. Generator used: <QLGenerator /Library/QuickLook/Video.qlgenerator>
[DEBUG] Loading <QLGenerator /Library/QuickLook/Video.qlgenerator>
[DEBUG] Previewing file:///Volumes/…/BigBuckBunny_2000hevc.mp4 finished
qlmanage[29574:377321] +[IKImageContentView _clampImageAlphaTo01:colorSpace:] no CIImage passed in
qlmanage[29574:377321] IKImageView2 _updateContentForLayerUsingIOSurface Error: source rect and destination rect of tile being drawn are not the same
```

For example the [BigBuckBunny_2000hevc.mp4](https://s3.amazonaws.com/x265.org/video/BigBuckBunny_2000hevc.mp4) (H.265 4K) file from the [x265.com samples](https://x265.com/hevc-video-files/) produces this error, but the [BigBuckBunny_2000h264.mp4](https://s3.amazonaws.com/x265.org/video/BigBuckBunny_2000h264.mp4) (H.264 4K) file plays back fine. The [Tractor_500kbps_x265.mp4](https://s3.amazonaws.com/x265.org/video/Tractor_500kbps_x265.mp4) (H.265 HD) also plays back fine. So it's not only about the codec, but some property of the compression or container that invokes the error.

Renaming the file from `.mp4` to `.m4v` as described in the Limitations section does not help.

`ffmpeg` does not reveal any significant codec differences (see failing video on right), other than frame rate and dimensions. Note however that the `sample_ascpect_ratio` and `display_aspect_ratio` fields seem to be messed up: `0:1`.

![diff](https://user-images.githubusercontent.com/1874498/51639582-8c70c400-1f61-11e9-88e0-4839b7600165.png)

macOS High Sierra 10.13.6 (17G4015), QLVideo 1.91 (installed via Homebrew)

**Comment by Duartede** [comment]
I have this problem:

Before installing QL Video the HEVC files would play well when I click on the space bar on finder but the files had no thumbnail. After installing QL Video the files have a thumbnail (although it takes sometime to load) but they won't play when I click the space bar in finder. They just open a still image like this I'm attaching. I'm running High Sierra (10.13.6). Can someone please help fix this? Thanks!
 
<img width="1704" alt="screen shot 2019-01-27 at 22 08 43" src="https://user-images.githubusercontent.com/47094193/51810749-25fce600-2280-11e9-9eeb-e86b18fe4ae9.png">
