### ISSUE TITLE
Thumbnail not working in Catalina 10.15

### ISSUE THREAD

**Issue by nirajshakya85** [Marginal/QLVideo#64]
I had just updated to mac os Catalina 10.15. But for some reason, QLVideo thumbnail does not work. I think this will work in Mojave. Waiting for an update..

**Comment by jeffbyrnes** [comment]
This is a duplicate of #63

**Comment by WreckWren** [comment]
If it's a duplicate of an issue from several months ago that really says a lot about the nature of this package's development, or total lack thereof.
