### ISSUE TITLE
Document where cache files are generated

### ISSUE THREAD

**Issue by lucasff** [Marginal/QLVideo#66]
Hello!

Important to privacy, I'd like to know where the cache/snapshots of videos are being saved. Is this cleared regularly? Can I create then, a scheduled cron job to clean up?

Thanks!

**Comment by Marginal** [comment]
Previews are generated "live" and aren't stored.

Thumbnails generated by this and by other QuickLook generators are stored in the folder $TMPDIR/../C/com.apple.QuickLook.thumbnailcache . This folder is protected by SIP so you'll have to [turn off SIP](https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/ConfiguringSystemIntegrityProtection/ConfiguringSystemIntegrityProtection.html#//apple_ref/doc/uid/TP40016462-CH5-SW1) to see it.

You can clear the thumbnails with `qlmanage -r cache`.
