### ISSUE TITLE
Unable to install v1.93

### ISSUE THREAD

**Issue by odebroqueville** [Marginal/QLVideo#68]
I'm getting the following system error message:

<img width="420" alt="Screenshot 2020-01-19 at 16 36 21" src="https://user-images.githubusercontent.com/4818315/72683729-13f00500-3ada-11ea-911b-dfd3ea73ce22.png">

**Comment by 3zero2** [comment]
What happens when you click on open?

**Comment by odebroqueville** [comment]
I get the same message!

**Comment by Eitot** [comment]
The package has not been notarised, which is a requirement in Catalina. It is code-signed though. You can still open it by right-clicking on it and selecting “Open” instead.

<img width="732" alt="Screenshot 2020-01-19 at 21 12 18" src="https://user-images.githubusercontent.com/15073177/72687676-8f64ad00-3b00-11ea-9e29-8aead95a88e6.png">

**Comment by odebroqueville** [comment]
Apologies, I somehow failed to notice the "Open" button in the dialog message! Silly me!
