### ISSUE TITLE
Installation successful but previews not working

### ISSUE THREAD

**Issue by sergej-m** [Marginal/QLVideo#70]
Hi guys. Hope you can help me out.

Running MacBook Pro 10.15.3, QLVideo 1.93.
Tried installing the package QLVideo_193.pkg normally and through Homebrew with the same result: installation successful (the generator is registered) but previews are not working.

Getting the following report when running qlmanage -p -d1 with any file:
```
2020-02-27 12:53:21.466 qlmanage[16699:683484] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x8f07, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2020-02-27 12:53:21.517 qlmanage[16699:683484] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xb80f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
```

Any ideas how to solve this? The latest release seems to work for others but not me 🙁

Cheers

**Comment by ksec** [comment]
Same problem.

**Comment by sergej-m** [comment]
Just tried re-installing one more time and restarting. Unfortunately it didn't work for me.

**Comment by ItsRyanWu** [comment]
> ~Same problem. It broke when I updated Catalina, I thought I will wait on updated preview function. Just installed it the updated release now, spent half an hour on it and couldn't figure out why it is still not working~
> 
> Turns out Finder relaunch and Log out doesn't work. But Restart did the trick.

Thank you! Restarting works for me

**Comment by hrguerra1980** [comment]
I'm having the same errors. My MBP is Intel on Big Sur and I've never been able to get QL to work no matter how many reboots and reinstalls. Any ideas?

**Comment by eirnym** [comment]
> I'm having the same errors. My MBP is Intel on Big Sur and I've never been able to get QL to work no matter how many reboots and reinstalls. Any ideas?

I'd suggest to try recompile and install it by yourself. 

I think it requires some effort from author to publish proper native M1 compatible with Big Sur.

**Comment by hrguerra1980** [comment]
I don’t know why but it works if I have VLC installed.

**Comment by sergej-m** [comment]
Wow, Guerra, you are a hero. I can confirm it working with VLC installed.
