### ISSUE TITLE
Preview icon become a green block since update to big sur

### ISSUE THREAD

**Issue by leedashone** [Marginal/QLVideo#73]
My QLVideo works fine when my mac at Catalina,, about 99% of MP4/H.264 file can see the thumbnail without problem.

A day I update OS to  Big Sur 11.0.1 ..... 99% of MP4/H.264 file thumbnail just a a green block.
(If switch Finder to list mode still can see some correct icon)

I try uninstall then re-install QLVideo,, also tryed "killall Finder" many times,, but the issue still exist.
(Also tryed reboot, power-off.....etc)

**Comment by acuntex** [comment]
I don't get any at all under Big Sur.

But given that the last update was in February, my best guess is that this project is dead. :-(

**Comment by acuntex** [comment]
Update: Works, except for .ts files
