### ISSUE TITLE
[suggest] I suggest install QLVideo to `~/Library/QuickLook/`

### ISSUE THREAD

**Issue by xiebruce** [Marginal/QLVideo#74]
I found that QLVideo installs to `/Library/QuickLook/` by Homebrew(which needs me input admin password), but most of other QuickLook plugin are install to `~/Library/QuickLook/`(still install by Homebrew), so I suggest install QLVideo to `~/Library/QuickLook/` too, at least, install to `~/Library/QuickLook/` when I'm not run brew with sudo.

**Comment by Marginal** [comment]
If you install the [pkg](https://github.com/Marginal/QLVideo/releases/latest) interactively rather than through Homebrew you have the choice of installing under ~/Library.
