### ISSUE TITLE
QLVideo crashing Finder with default settings on Big Sur/Apple Silicon.

### ISSUE THREAD

**Issue by eppic6502** [Marginal/QLVideo#75]
With the default of ```defaults write uk.org.marginal.qlvideo SnapshotAlways -bool XX``` , QLVideo keeps crashing Finder as soon as it's trying to preview a video in the side panel on Apple Silicon macs with Big Sur.
Changing the option to ```defaults write uk.org.marginal.qlvideo SnapshotAlways -bool YES``` seems to have fixed it, so I'd suggest making that the default option for future releases, as a temporary fix.

**Comment by Marginal** [comment]
`defaults write uk.org.marginal.qlvideo SnapshotAlways -bool XX` should give an error. Did you mean `defaults write uk.org.marginal.qlvideo SnapshotAlways -bool NO`?

In any case please try with Release 1.94 which adds untested support for ARM-based Macs.

**Comment by Marginal** [comment]
Should be fixed in Release 1.96
