### ISSUE TITLE
Brew package SHA256 mismatch

### ISSUE THREAD

**Issue by wattsie** [Marginal/QLVideo#81]
Wondering who maintains the Brew package?
(https://formulae.brew.sh/api/cask/qlvideo.json)

Upgrading to 1.94 fails.

```
=> Upgrading 1 outdated package:
qlvideo 1.93 -> 1.94
==> Upgrading qlvideo
==> Downloading https://github.com/Marginal/QLVideo/releases/download/rel-194/QLVideo_194.pkg
Already downloaded: /Users/shane/Library/Caches/Homebrew/downloads/546165cd0e5ada7016971802b1c7603f46ecda02930b17303ddafacf1ef24ee1--QLVideo_194.pkg
==> Purging files for version 1.94 of Cask qlvideo
Error: qlvideo: SHA256 mismatch
Expected: a497bd1facd041c1e51fecc24060a7a02bfbeaa859c891aa33ebbe315018847f
  Actual: 94db54232f82588b63da78194f407a0dbff690f36e3fc0e9fb4220398b16efa2
```

**Comment by wattsie** [comment]
Never mind, looks like the brew json file it just got updated...
Cheers.

**Comment by Marginal** [comment]
Thanks for raising anyway

**Comment by ZTfer** [comment]
Same Here

brew install qlvideo

Downloading https://github.com/Marginal/QLVideo/releases/download/rel-194/QL
Already downloaded: /Users/ztfer/Library/Caches/Homebrew/downloads/546165cd0e5ada7016971802b1c7603f46ecda02930b17303ddafacf1ef24ee1--QLVideo_194.pkg
Error: SHA256 mismatch
Expected: a497bd1facd041c1e51fecc24060a7a02bfbeaa859c891aa33ebbe315018847f
  Actual: 94db54232f82588b63da78194f407a0dbff690f36e3fc0e9fb4220398b16efa2

**Comment by ZTfer** [comment]
See here https://github.com/caskformula/homebrew-caskformula/issues/63

run `brew cleanup --prune=0`, and everything was fine
