### ISSUE TITLE
I have MacOs Big Sur and It Doesn't work for me.

### ISSUE THREAD

**Issue by beemybold** [Marginal/QLVideo#85]
Last login: Fri May 21 04:41:26 on ttys000
bemy-bold@MacBook-Pro-de-Bernado ~ %     qlmanage -p -d1 /Users/bemy-bold/Downloads/\[\ OxTorrent.com\ \]\ Vis\ A\ Vis\ S01\ FRENCH\ HDTV\ XviD-EXTREME/Vis.A.Vis.S01E01.FRENCH.HDTV.XviD-EXTREME.avi
qlmanage: illegal option for p -- 
Usage: qlmanage [OPTIONS] path...
	-h		Display this help
	-r		Force reloading Generators list
	-r cache	Reset thumbnail disk cache
	-m [name ...]	Display statistics about quicklookd. Stats names:
			* plugins	Show the generators list
			* server	Show quicklookd life information
			* memory	Show quicklookd memory consumption
			* burst		Show statistics about the last burst
			* threads	Show concurrent accesses stats
			* other		Show other information about quicklookd
	-p		Compute previews of the documents
	-t		Compute thumbnails of the documents
	-x		Use quicklookd (remote computation)
	-i		Compute thumbnail in icon mode
	-s size		Size for the thumbnail
	-f factor	Scale factor for the thumbnail
	-F factor	Scale factor for the thumbnail, draw downscaled and compare to 1x
	-z		Display generation performance info (don't display thumbnails)
	-o dir		Output result in dir (don't display thumbnails or previews)
	-c contentType	Force the content type used for the documents
	-g generator	Force the generator to use

bemy-bold@MacBook-Pro-de-Bernado ~ %

**Comment by jkgreen** [comment]
Last login: Fri May  6 18:07:42 on ttys000
jkgreen@JKs-MacBook-Pro-New ~ % qlmanage /Volumes/HD8/VISUALS/VISUALS\ HITNRUN/NEW_RANDOM_HAP -t
Testing Quick Look thumbnails with files:
	/Volumes/HD8/VISUALS/VISUALS HITNRUN/NEW_RANDOM_HAP
2022-05-09 11:09:40.121 qlmanage[16470:796354] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x6b03, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.

**Comment by Marginal** [comment]
Fixed in Release 1.96
