### ISSUE TITLE
MacBook Air M1: The plugin doesn't work with .avi files. (+debug)

### ISSUE THREAD

**Issue by sohate** [Marginal/QLVideo#86]
Doesn't work with .avi files. Debug:

escapist@183eeff10f4a ~ % 
  [Restored 25 May 2021, 10:31:51]
Last login: Tue May 25 10:29:48 on ttys000
Restored session: Tue May 25 10:31:50 +09 2021
escapist@183eeff10f4a ~ % qlmanage -m
server: living for 237s (0 requests handled) - instant off: yes - arch: ARM64 - user id: 501
memory used: 0 MB (1008720 bytes) - used descriptors: 19/256
plugins:
  org.videolan.avi -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.perian.nuppelvideo -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.iwork.keynote.sffkth -> /System/Library/QuickLook/iWork.qlgenerator (221)
  org.openemu.savestate -> /Applications/OpenEmu.app/Contents/Library/QuickLook/OESaveStateQLPlugin.qlgenerator (1.0)
  com.microsoft.powerpoint.pot -> /System/Library/QuickLook/Office.qlgenerator (41)
  org.videolan.wmv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.perian.ogv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.ogg-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.massanti.mediainfomac.flash-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.mpv.divx -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.audio -> /System/Library/QuickLook/Audio.qlgenerator (928.3)
  io.iina.flash -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.xiph.ogv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.iwork.pages.sfftemplate -> /System/Library/QuickLook/iWork.qlgenerator (221)
  com.macblurayplayer.nuppelvideo -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.flc-animation -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.smpte.gxf -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.iina.3gpp2 -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.asf -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.adobe.illustrator.ai-image -> /System/Library/QuickLook/EPS.qlgenerator (928.3)
  io.mpv.rmvb -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.mpeg-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.plain-text -> /System/Library/QuickLook/Text.qlgenerator (928.3)
  public.x509-printable-encoded-archive -> /System/Library/QuickLook/Security.qlgenerator (55149.120.1)
  com.apple.ibooks-folder -> /System/Library/QuickLook/iBooks.qlgenerator (1)
  io.mpv.webm -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.movie -> /System/Library/QuickLook/Movie.qlgenerator (928.3)
  com.real.realvideo -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.iwork.keynote.key -> /System/Library/QuickLook/iWork.qlgenerator (221)
  com.apple.ical.bookmark -> /System/Library/QuickLook/iCal.qlgenerator (928.3)
  org.niltsh.mplayerx-xvid -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.rsa.pkcs-12 -> /System/Library/QuickLook/Security.qlgenerator (55149.120.1)
  com.apple.keychain -> /System/Library/QuickLook/Security.qlgenerator (55149.120.1)
  org.videolan.mxf -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.realmedia -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.mkv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.iwork.numbers.sffnumbers -> /System/Library/QuickLook/iWork.qlgenerator (221)
  public.audiovisual-content -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.openxmlformats.spreadsheetml.sheet -> /System/Library/QuickLook/Office.qlgenerator (41)
  com.real.realmedia-vbr -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.rec -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.x509-certificate -> /System/Library/QuickLook/Security.qlgenerator (55149.120.1)
  com.blurayplayersoftware.divx -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.ichat.ichat -> /System/Library/QuickLook/iChat.qlgenerator (5500)
  com.apple.iwork.numbers.numbers-tef -> /System/Library/QuickLook/iWork.qlgenerator (221)
  io.iina.mkv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.iina.realmedia -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.localized-pdf-bundle -> /System/Library/QuickLook/LocPDF.qlgenerator (928.3)
  com.adobe.encapsulated-postscript -> /System/Library/QuickLook/EPS.qlgenerator (928.3)
  com.apple.ical.bookmark.todo -> /System/Library/QuickLook/iCal.qlgenerator (928.3)
  com.apple.ical.ics.event -> /System/Library/QuickLook/iCal.qlgenerator (928.3)
  org.videolan.nsv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.xhtml -> /System/Library/QuickLook/Web.qlgenerator (928.3)
  org.niltsh.mplayerx-flash-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.mpv.ogv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.property-list -> /System/Library/QuickLook/Text.qlgenerator (928.3)
  com.microsoft.excel.xlt -> /System/Library/QuickLook/Office.qlgenerator (41)
  com.apple.iwork.keynote.sffkey -> /System/Library/QuickLook/iWork.qlgenerator (221)
  com.massanti.mediainfomac.mpeg2 -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.iconset -> /System/Library/QuickLook/Icon.qlgenerator (928.3)
  com.microsoft.wtv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.canon.raw.movie -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.nuv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.openxmlformats.spreadsheetml.template -> /System/Library/QuickLook/Office.qlgenerator (41)
  com.apple.pict -> /System/Library/QuickLook/Clippings.qlgenerator (928.3)
  public.vcard -> /System/Library/QuickLook/Contact.qlgenerator (928.3)
  com.adobe.pdf -> /System/Library/QuickLook/PDF.qlgenerator (928.3)
  org.perian.flash-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.google.webm -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.idpf.epub-folder -> /System/Library/QuickLook/iBooks.qlgenerator (1)
  io.iina.wmv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.tod -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.niltsh.mplayerx-mxf -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.mpv.flv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.flash -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.rtf -> /System/Library/QuickLook/Text.qlgenerator (928.3)
  com.apple.iwork.pages.pages-tef -> /System/Library/QuickLook/iWork.qlgenerator (221)
  io.iina.mpeg4-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.package -> /System/Library/QuickLook/Package.qlgenerator (928.3)
  com.microsoft.windows-media-wmv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.niltsh.mplayerx-mts -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.microsoft.word.stationery -> /System/Library/QuickLook/Office.qlgenerator (41)
  com.apple.iwork.pages.sffpages -> /System/Library/QuickLook/iWork.qlgenerator (221)
  com.microsoft.xesc -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.iwork.keynote.key-tef -> /System/Library/QuickLook/iWork.qlgenerator (221)
  org.openxmlformats.presentationml.slideshow -> /System/Library/QuickLook/Office.qlgenerator (41)
  com.apple.addressbook.person -> /System/Library/QuickLook/Contact.qlgenerator (928.3)
  io.iina.avi -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.matroska.mkv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.iwork.numbers.sfftemplate -> /System/Library/QuickLook/iWork.qlgenerator (221)
  org.openxmlformats.presentationml.presentation.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (41)
  com.apple.webarchive -> /System/Library/QuickLook/Web.qlgenerator (928.3)
  com.apple.private.live-photo-bundle -> /System/Library/QuickLook/LivePhoto.qlgenerator (928.3)
  io.mpv.mkv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.massanti.mediainfomac.matroska -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.safari.history -> /System/Library/QuickLook/Bookmark.qlgenerator (928.3)
  org.niltsh.mplayerx-divx -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.mpv.dv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.keynote.key -> /System/Library/QuickLook/iWork.qlgenerator (221)
  public.comma-separated-values-text -> /System/Library/QuickLook/Office.qlgenerator (41)
  org.openxmlformats.wordprocessingml.template.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (41)
  org.videolan.axv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.systempreference.prefpane -> /System/Library/QuickLook/StandardBundles.qlgenerator (928.3)
  org.niltsh.mplayerx-dv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.ichat.transcript -> /System/Library/QuickLook/iChat.qlgenerator (5500)
  com.apple.addressbook.group -> /System/Library/QuickLook/Contact.qlgenerator (928.3)
  org.videolan.mpeg-stream -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.mpv.avi -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.openxmlformats.wordprocessingml.document -> /System/Library/QuickLook/Office.qlgenerator (41)
  com.apple.iwork.pages.pages -> /System/Library/QuickLook/iWork.qlgenerator (221)
  org.smpte.mxf -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.iwork.keynote.kth -> /System/Library/QuickLook/iWork.qlgenerator (221)
  org.openxmlformats.wordprocessingml.template -> /System/Library/QuickLook/Office.qlgenerator (41)
  io.iina.dv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.xesc -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.massanti.mediainfomac.mpeg2ts -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.protected-mpeg-4-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.internet-location -> /System/Library/QuickLook/Clippings.qlgenerator (928.3)
  io.iina.asf -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.divx.divx -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.massanti.mediainfomac.nuppelvideo -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.iina.ogg-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.iwork.numbers.numbers -> /System/Library/QuickLook/iWork.qlgenerator (221)
  org.videolan.wtv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.ical.ics -> /System/Library/QuickLook/iCal.qlgenerator (928.3)
  org.openxmlformats.presentationml.template.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (41)
  org.videolan.3gp -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  indy.jt.niceplayer.mkv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.dv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.idpf.epub-container -> /System/Library/QuickLook/iBooks.qlgenerator (1)
  com.blurayplayersoftware.nuppelvideo -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.image -> /System/Library/QuickLook/Image.qlgenerator (928.3)
  io.iina.quicktime -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.iina.webm -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.tv.movpkg -> /System/Library/QuickLook/Movie.qlgenerator (928.3)
  org.openxmlformats.presentationml.slideshow.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (41)
  com.apple.iwork.numbers.template -> /System/Library/QuickLook/iWork.qlgenerator (221)
  com.microsoft.word.doc -> /System/Library/QuickLook/Office.qlgenerator (41)
  com.apple.ical.ics.todo -> /System/Library/QuickLook/iCal.qlgenerator (928.3)
  com.apple.safari.bookmark -> /System/Library/QuickLook/Bookmark.qlgenerator (928.3)
  io.mpv.wma -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  indy.jt.niceplayer.divx -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.microsoft.powerpoint.ppt -> /System/Library/QuickLook/Office.qlgenerator (41)
  org.niltsh.mplayerx-ogg-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.iina.wtv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.microsoft.windows-media-wm -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.perian.divx -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.microsoft.advanced-systems-format -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.finder.pictclipping -> /System/Library/QuickLook/Clippings.qlgenerator (928.3)
  org.videolan.divx -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.iina.mpeg-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.font -> /System/Library/QuickLook/Font.qlgenerator (928.3)
  org.oasis-open.opendocument.text -> /System/Library/QuickLook/Text.qlgenerator (928.3)
  public.html -> /System/Library/QuickLook/Web.qlgenerator (928.3)
  org.openxmlformats.presentationml.presentation -> /System/Library/QuickLook/Office.qlgenerator (41)
  public.xml -> /System/Library/QuickLook/Text.qlgenerator (928.3)
  org.webmproject.webm -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.openxmlformats.spreadsheetml.sheet.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (41)
  com.massanti.mediainfomac.ogv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.openxmlformats.spreadsheetml.template.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (41)
  org.niltsh.mplayerx-matroska-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.niltsh.mplayerx-rmvb -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.application -> /System/Library/QuickLook/StandardBundles.qlgenerator (928.3)
  com.blurayplayersoftware.ogv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.openxmlformats.presentationml.template -> /System/Library/QuickLook/Office.qlgenerator (41)
  com.microsoft.windows-media-wmp -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.rtfd -> /System/Library/QuickLook/Text.qlgenerator (928.3)
  io.mpv.xvid -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.microsoft.powerpoint.pps -> /System/Library/QuickLook/Office.qlgenerator (41)
  public.json -> /System/Library/QuickLook/Text.qlgenerator (928.3)
  org.mythtv.nuppelvideo -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.microsoft.excel.xls -> /System/Library/QuickLook/Office.qlgenerator (41)
  public.svg-image -> /System/Library/QuickLook/Web.qlgenerator (928.3)
  org.perian.matroska -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.adobe.flash.video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.gxf -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.vro -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.macblurayplayer.matroska -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.openxmlformats.wordprocessingml.document.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (41)
  com.real.realmedia -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.quicktime -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.macblurayplayer.divx -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.finder.textclipping -> /System/Library/QuickLook/Clippings.qlgenerator (928.3)
  com.microsoft.word.dot -> /System/Library/QuickLook/Office.qlgenerator (41)
  com.apple.iwork.pages.template -> /System/Library/QuickLook/iWork.qlgenerator (221)
  com.blurayplayersoftware.matroska -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.webm -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.mpv.wmv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.iina.divx -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.iina.3gpp -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.macblurayplayer.ogv -> /Library/QuickLook/Video.qlgenerator (1.9.4)

escapist@183eeff10f4a ~ % qlmanage -p "/Volumes/External1/Разные фильмы/Традиционные фильмы/Фильмы/Alice in Wonderland.avi"
Testing Quick Look preview with files:
	/Volumes/External1/Разные фильмы/Традиционные фильмы/Фильмы/Alice in Wonderland.avi
2021-05-25 10:32:42.601 qlmanage[869:15358] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x7903, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2021-05-25 10:32:42.628 qlmanage[869:15358] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xb61b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2021-05-25 10:32:48.467 qlmanage[869:15359] Persistent UI failed to open file file:///Users/escapist/Library/Saved%20Application%20State/com.apple.quicklook.qlmanage.savedState/window_2.data: No such file or directory (2)
escapist@183eeff10f4a ~ % qlmanage -p "/Volumes/External1/Разные фильмы/Традиционные фильмы/Фильмы/Alice in Wonderland.avi"
Testing Quick Look preview with files:
	/Volumes/External1/Разные фильмы/Традиционные фильмы/Фильмы/Alice in Wonderland.avi
2021-05-25 10:32:53.362 qlmanage[871:15569] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x7c03, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2021-05-25 10:32:53.384 qlmanage[871:15569] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x14b1b, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2021-05-25 10:32:55.140 qlmanage[871:15573] Persistent UI failed to open file file:///Users/escapist/Library/Saved%20Application%20State/com.apple.quicklook.qlmanage.savedState/window_2.data: No such file or directory (2)

**Comment by wmrichard** [comment]
+1 MacBook Air m1 is working fine (thanks for the update). But it looks like avi isn't supported at the moment. Thanks for the last update!

**Comment by JeffH1987** [comment]
Bump for old Intel Core i5. AVI does not get the thumbnails. Definitely working with FLV and MKV. Seems like a Big Sur issue ...?

**Comment by Marginal** [comment]
Unfortunately this is a limitation of Catalina & Big Sur. macOS can't produce thumbnails or previews itself for most(all?) AVI files, but won't let other quicklook plugins have a shot. (On the upside Catalina and later allow for live previews of non-native video files such as MKV, which I hope to add support for in a future release). 

I'm glad it works at all on m1 - I don't have access to one to test.
