### ISSUE TITLE
kMDItemVideoBitRate

### ISSUE THREAD

**Issue by mlanglois** [Marginal/QLVideo#9]
kMDItemAudioBitRate is present, but not kMDItemVideoBitRate.
Could it be added? Perhaps other metadata as well, but this is the one I need! ^^
Many thanks for such a great software!!

**Comment by Marginal** [comment]
QLVideo reports kMDItemVideoBitRate for those cases where the value is easily calculable. For other cases I haven't found a cheap enough way of determining the video bitrate. Marking this as wontfix.
