### ISSUE TITLE
Not work with M1 chip

### ISSUE THREAD

**Issue by Barny96** [Marginal/QLVideo#90]
installation is normal, after it does not work, even log out log in.

**Comment by eirnym** [comment]
Hi @Barny96, it's probably need to be rebuilt before it starts to work.

**Comment by Barny96** [comment]
Hi Arseny Nasokin, thanks for reply, I will wait.  :) have a good day.

**Comment by eirnym** [comment]
I compiled by myself. It is easier than you might think. No need to be a programmer

**Comment by Barny96** [comment]
Did you upload yet lol

**Comment by eirnym** [comment]
You hit the problem, I proposed a viable solution to make it fast and easy on your own. 

As you see, I'm not a maintainer of this repo, nor author to prepare a release.

**Comment by Barny96** [comment]
Alright, that’s find haha thanks

**Comment by Barny96** [comment]
If you know how to rebuild

**Comment by eirnym** [comment]
BUILDING.md file has instructions. All you need to install beforehand is Xcode and allow development on your macOS. Maybe you need to create a personal certificate, it's easy to do, google will help you with this.

**Comment by frozenpandaman** [comment]
Working for me, via Homebrew, fwiw.

**Comment by tabasko78** [comment]
current version works fine on my MBP M1 pro.
