### ISSUE TITLE
AVI and MKV not showing thumbnails in Finder on Monterey 12.0.1.

### ISSUE THREAD

**Issue by Jcs16** [Marginal/QLVideo#92]

**Comment by frozenpandaman** [comment]
Works fine for me with .mkv files. Installed via Homebrew.

Some .avi files work and some dont – from what I can tell, its only those with the MJPG codec. Others (DV, Xvid, DivX, etc.) dont have a preview displayed.

**Comment by Jcs16** [comment]
Thanks frozenpandaman. My Divx files show a preview. I did NOT install via homebrew. Wonder if that's what the issue is - different installation methods?

**Comment by tabasko78** [comment]
Worked for me on Monterey with you last current version QLVideo_194.pkg (thumbs and preview for MKV files)
Don't forget to kill and restart the Finder !
Doesn't work for AVI :(

**Comment by Marginal** [comment]
Support for .avi files is restored in version 1.96
