### ISSUE TITLE
Some .mkv files show as corrupted

### ISSUE THREAD

**Issue by frozenpandaman** [Marginal/QLVideo#93]
e.g.
![image](https://user-images.githubusercontent.com/7245874/141605146-2556c8f0-bf19-4883-8616-d07cf416bbdd.png)

![image](https://user-images.githubusercontent.com/7245874/141605176-2fed7f18-2c7c-4eee-8be6-597de07ef105.png)

**Comment by eirnym** [comment]
Hi, have you tried to re-index them like HandBrake does?

**Comment by frozenpandaman** [comment]
@eirnym What do you mean?

**Comment by eirnym** [comment]
Handbrake has a feature to rebuild time-to-frame indices in a video file. Sometimes indices became corrupted and video could be still playable, but automated tools can give strange output. "Force re-index" process usually fixes these issues, full re-encoding is not required, but also helpful. 

Basically, this plugin does sampling video file at specific moments using ffmpeg library. You can try to fetch some screenshots by yourself based using ffmpeg using something like following command `ffmpeg -ss 01:23:45 -i input -vframes 1 -q:v 2 output.jpg`.

**Comment by frozenpandaman** [comment]
Thanks! It's likely just a problem with the video file itself, then. I think some users would want to preserve the files exactly from the source they're downloaded, so modifying the video (i.e. the md5 hash or bytes changing in any way) or re-encoding isn't always an option. Can you point me to the Handbrake [command](https://handbrake.fr/docs/en/latest/cli/command-line-reference.html) that does this? I can't find the option in the GUI either, but would be interested to try it out per your suggestion.

You're right – the ffmpeg command you provided outputs a similarly (though not identically) messed up screenshot. Wonder if there's any way to fix this, since it does display properly during playback, when scrubbing to it, etc.?

**Comment by frozenpandaman** [comment]
Also (maybe this is different enough to deserve its own issue?) I've noticed some files, particular those with large file sizes, show up as having completely black thumbnails:
<img width="595" src="https://user-images.githubusercontent.com/7245874/141671082-ecc01759-5201-4469-980d-85f493acb257.png">
However, clicking on one of the sidebar thumbnails displays the full image, but the sidebar remains black:
<img width="595" src="https://user-images.githubusercontent.com/7245874/141671108-b6d9e1fd-d5f6-456a-8ca8-b3faeb873973.png">
Sometimes when viewing the file in Quick Look, a few of the images show, but not all, and it's often different ones each time:
<img width="595" src="https://user-images.githubusercontent.com/7245874/141671130-4539e1d7-cf00-474a-b21e-621411e3f452.png">

**Comment by eirnym** [comment]
Reindexing usually solves the problem. 
Basically in most cases there's 2 kind of frames: full image frame with full image and motion frame. Index shows where full frames are for fast forward feature.

**Comment by eirnym** [comment]
Not all sources have good files in them. Broken video files and won't be shown correctly except you're lucky enough as you described.

**Comment by frozenpandaman** [comment]
>Reindexing usually solves the problem.

Could you point me how to do this? I didn't see the option looking through the Handbrake CLI tools or GUI.

**Comment by eirnym** [comment]
really, thanks for noticing me :) it uses ffmpeg underneath, so I found answer fairly quickly 

Tell ffmpeg to put into a new container (even with the same format and video/audio streams will be copied as they are)`ffmpeg -i infile -c:v copy -c:a copy outfile` or recode as you pleased.

**Comment by eirnym** [comment]
My guess is it's possible to make the same with Handbrake GUI, probably by adding this action as a new preset (without recoding video and audio)

**Comment by frozenpandaman** [comment]
Ah, you just meant "fix" it like that, got it. I'm happy (and more comfortable) with using `ffmpeg` anyway – you just mentioned Handbrake before, so I was going off that.

However, running that command doesn't fix *either* of the issues ([black thumbnails](https://github.com/Marginal/QLVideo/issues/93#issuecomment-968241012) and [corrupted thumbnails](https://github.com/Marginal/QLVideo/issues/93#issue-1052537842)). For the former, at least, it's **not an issue with the video file** – it's an issue with QLVideo, likely due to the file size.

**Comment by eirnym** [comment]
I used Handbrake for this back in the day. 

Returning to your question, does ffmpeg returns correct images?

**Comment by frozenpandaman** [comment]
>does ffmpeg returns correct images?

"the ffmpeg command you provided outputs a similarly (though not identically) messed up screenshot" https://github.com/Marginal/QLVideo/issues/93#issuecomment-968240959

**Comment by eirnym** [comment]
Probably you should file an issue to ffmpeg itself then. I'd love to know any way how to fix these video files as well

**Comment by Marginal** [comment]
If FFmpeg doesn't like the file then unfortunately QLVideo won't either. Closing.
