### ISSUE TITLE
Cannot install because signature is invalid or corrupted

### ISSUE THREAD

**Issue by Jolanxbl** [Marginal/QLVideo#94]
Mavericks

![image](https://user-images.githubusercontent.com/94738963/161369919-8823ae8d-f64c-45b1-bd5e-cf51d3828b7e.png)

**Comment by Ulrik54** [comment]
Installing with Homebrew (El Capitan) yields following error message:
`Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=ulrik USER=ulrik USERNAME=ulrik /usr/sbin/installer -pkg /usr/local/Caskroom/qlvideo/1.94/QLVideo_194.pkg -target /` exited with 1. Here's the output:
installer: Package name is QuickLook Video
installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.`
Where to put the `-allowUntrusted` command?

**Comment by craigalness** [comment]
Hi, Is there a workaround for Monterey 12.5 (21G72)?
Craig

**Comment by Ulrik54** [comment]
Unless `pkgutil` works in Monterey as well, I have no idea. I have never installed anything newer than El Capitan.

**Comment by craigalness** [comment]
Hey, thanks for the reply, I will give it a try.

**Comment by craigalness** [comment]
I was able to successfully install but preview is still not working after reboot. Might be a codec in the mp4 from a Sony FX3 that is not compatible Thanks for the help.

**Comment by eirnym** [comment]
@craigalness could you please try to open it in mpv (the easiest way) and similar software?

**Comment by Marginal** [comment]
Fixed in release 1.96

**Comment by Ulrik54** [comment]
After the update, it no longer works on older systems (which is what OP and I were reporting issues on in the first place). Current solution using pkgutil still applies until a fix is implemented.
