### ISSUE TITLE
Big Sur HAP Support

### ISSUE THREAD

**Issue by jkgreen** [Marginal/QLVideo#95]
Im trying to get this working on Big Sur to preview HAP, it doesnt seem to be working.
Can anybody offer any help.

I really need to be able to preview HAP on my mac for video shows.

I can currently use Adobe Bridge but it is very system intensive so not ideal.

Many Thanks

**Comment by eirnym** [comment]
Could you share a little bit of information?

1) what the HAP is? I found too little information about
2) Is this format (I suppose I'm correct here) supported by `ffmpeg`/`mkv`?

**Comment by Marginal** [comment]
Apparently, according to https://hap.video/integrations.html, QLVideo already supports HAP. Closing.
Please use **Help** → **Report an Issue** in the app if you're still seeing problems with [release 2.00](https://github.com/Marginal/QLVideo/releases/latest), as described [here](https://github.com/Marginal/QLVideo/wiki/Troubleshooting#to-report-an-issue).
