### ISSUE TITLE
QLVideo 194 not working on my M1 Mac

### ISSUE THREAD

**Issue by YashiroKirara** [Marginal/QLVideo#96]
Last login: Fri Jul 15 12:53:20 on ttys000
yashiro@SKYRIM ~ % qlmanage -m
server: living for 27s (0 requests handled) - instant off: yes - arch: ARM64 - user id: 501
memory used: 0 MB (569984 bytes) - used descriptors: 19/256
plugins:
  org.videolan.avi -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.perian.nuppelvideo -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.iwork.keynote.sffkth -> /System/Library/QuickLook/iWork.qlgenerator (225)
  org.tukaani.xz-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  org.openemu.savestate -> /Applications/OpenEmu.app/Contents/Library/QuickLook/OESaveStateQLPlugin.qlgenerator (1.0)
  com.microsoft.powerpoint.pot -> /System/Library/QuickLook/Office.qlgenerator (46)
  org.videolan.wmv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.perian.ogv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.parallels.vm.vmpackage.packed -> /Applications/Parallels Desktop.app/Contents/Library/QuickLook/ParallelsQL.qlgenerator (51548)
  public.cpio-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  org.videolan.ogg-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.massanti.mediainfomac.flash-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.mpv.divx -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.parallels.vm.vmpackage -> /Applications/Parallels Desktop.app/Contents/Library/QuickLook/ParallelsQL.qlgenerator (51548)
  io.iina.flash -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.xiph.ogv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.iwork.pages.sfftemplate -> /System/Library/QuickLook/iWork.qlgenerator (225)
  public.audio -> /System/Library/QuickLook/Audio.qlgenerator (950.2)
  com.macblurayplayer.nuppelvideo -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.flc-animation -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.vmware.foreign.pvm -> /Applications/Parallels Desktop.app/Contents/Library/QuickLook/ParallelsQL.qlgenerator (51548)
  org.gnu.gnu-tar-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  org.smpte.gxf -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.iina.3gpp2 -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.asf -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.adobe.illustrator.ai-image -> /System/Library/QuickLook/Illustrator.qlgenerator (950.2)
  org.xmind.openformat.xmt -> /Applications/XMind.app/Contents/Library/QuickLook/XMindQuickLook.qlgenerator (1.0)
  io.mpv.rmvb -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.mpeg-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  cx.c3.lha-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  public.plain-text -> /System/Library/QuickLook/Text.qlgenerator (950.2)
  public.x509-printable-encoded-archive -> /System/Library/QuickLook/Security.qlgenerator (55159.100.4)
  io.mpv.webm -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.rarlab.rar-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  public.movie -> /System/Library/QuickLook/Movie.qlgenerator (950.2)
  public.bzip2-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  cx.c3.pax-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  com.real.realvideo -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.iwork.keynote.key -> /System/Library/QuickLook/iWork.qlgenerator (225)
  com.apple.ical.bookmark -> /System/Library/QuickLook/iCal.qlgenerator (950.2)
  org.niltsh.mplayerx-xvid -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.rsa.pkcs-12 -> /System/Library/QuickLook/Security.qlgenerator (55159.100.4)
  com.apple.keychain -> /System/Library/QuickLook/Security.qlgenerator (55159.100.4)
  cx.c3.arc-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  org.videolan.mxf -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.realmedia -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.mkv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.iwork.numbers.sffnumbers -> /System/Library/QuickLook/iWork.qlgenerator (225)
  public.audiovisual-content -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.openxmlformats.spreadsheetml.sheet -> /System/Library/QuickLook/Office.qlgenerator (46)
  com.real.realmedia-vbr -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.rec -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.x509-certificate -> /System/Library/QuickLook/Security.qlgenerator (55159.100.4)
  com.blurayplayersoftware.divx -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.ichat.ichat -> /System/Library/QuickLook/iChat.qlgenerator (5500)
  com.apple.iwork.numbers.numbers-tef -> /System/Library/QuickLook/iWork.qlgenerator (225)
  io.iina.mkv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.iina.realmedia -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.tukaani.lzma-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  com.apple.localized-pdf-bundle -> /System/Library/QuickLook/LocPDF.qlgenerator (950.2)
  com.apple.ical.ics.event -> /System/Library/QuickLook/iCal.qlgenerator (950.2)
  com.apple.ical.bookmark.todo -> /System/Library/QuickLook/iCal.qlgenerator (950.2)
  org.videolan.nsv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.xhtml -> /System/Library/QuickLook/Web.qlgenerator (950.2)
  org.niltsh.mplayerx-flash-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.sogou.pinyin.mssf -> /Library/QuickLook/SogouSkinFileQuickLook.qlgenerator (1.1)
  io.mpv.ogv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.property-list -> /System/Library/QuickLook/Text.qlgenerator (950.2)
  com.microsoft.excel.xlt -> /System/Library/QuickLook/Office.qlgenerator (46)
  com.apple.iwork.keynote.sffkey -> /System/Library/QuickLook/iWork.qlgenerator (225)
  com.massanti.mediainfomac.mpeg2 -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.iconset -> /System/Library/QuickLook/Icon.qlgenerator (950.2)
  com.microsoft.wtv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.canon.raw.movie -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.nuv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.openxmlformats.spreadsheetml.template -> /System/Library/QuickLook/Office.qlgenerator (46)
  com.apple.pict -> /System/Library/QuickLook/Clippings.qlgenerator (950.2)
  public.vcard -> /System/Library/QuickLook/Contact.qlgenerator (950.2)
  public.tar-bzip2-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  org.perian.flash-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.adobe.pdf -> /System/Library/QuickLook/PDF.qlgenerator (950.2)
  com.google.webm -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.zip-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  com.microsoft.cab-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  io.iina.wmv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.tod -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.niltsh.mplayerx-mxf -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.mpv.flv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.flash -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.rtf -> /System/Library/QuickLook/Text.qlgenerator (950.2)
  com.apple.iwork.pages.pages-tef -> /System/Library/QuickLook/iWork.qlgenerator (225)
  io.iina.mpeg4-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.package -> /System/Library/QuickLook/Package.qlgenerator (950.2)
  com.microsoft.windows-media-wmv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.niltsh.mplayerx-mts -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.tukaani.xz-tar-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  com.microsoft.word.stationery -> /System/Library/QuickLook/Office.qlgenerator (46)
  com.apple.iwork.pages.sffpages -> /System/Library/QuickLook/iWork.qlgenerator (225)
  com.microsoft.xesc -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.iwork.keynote.key-tef -> /System/Library/QuickLook/iWork.qlgenerator (225)
  org.openxmlformats.presentationml.slideshow -> /System/Library/QuickLook/Office.qlgenerator (46)
  com.apple.addressbook.person -> /System/Library/QuickLook/Contact.qlgenerator (950.2)
  io.iina.avi -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.iso-image -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  org.matroska.mkv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.iwork.numbers.sfftemplate -> /System/Library/QuickLook/iWork.qlgenerator (225)
  org.openxmlformats.presentationml.presentation.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (46)
  com.apple.webarchive -> /System/Library/QuickLook/Web.qlgenerator (950.2)
  org.7-zip.7-zip-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  org.xmind.openformat.xmind -> /Applications/XMind.app/Contents/Library/QuickLook/XMindQuickLook.qlgenerator (1.0)
  com.apple.private.live-photo-bundle -> /System/Library/QuickLook/LivePhoto.qlgenerator (950.2)
  io.mpv.mkv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.gnu.gnu-zip-tar-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  com.massanti.mediainfomac.matroska -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.safari.history -> /System/Library/QuickLook/Bookmark.qlgenerator (950.2)
  org.niltsh.mplayerx-divx -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.mpv.dv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.agilebits.itemmetadata -> /Applications/1Password 7.app/Contents/Library/QuickLook/OPItemMetadataQLGenerator.qlgenerator (70905002)
  com.apple.keynote.key -> /System/Library/QuickLook/iWork.qlgenerator (225)
  public.comma-separated-values-text -> /System/Library/QuickLook/Office.qlgenerator (46)
  org.openxmlformats.wordprocessingml.template.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (46)
  org.videolan.axv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.systempreference.prefpane -> /System/Library/QuickLook/StandardBundles.qlgenerator (950.2)
  com.parallels.vm.vmpackage.compressed -> /Applications/Parallels Desktop.app/Contents/Library/QuickLook/ParallelsQL.qlgenerator (51548)
  org.niltsh.mplayerx-dv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.ichat.transcript -> /System/Library/QuickLook/iChat.qlgenerator (5500)
  com.apple.addressbook.group -> /System/Library/QuickLook/Contact.qlgenerator (950.2)
  org.videolan.mpeg-stream -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.mpv.avi -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.openxmlformats.wordprocessingml.document -> /System/Library/QuickLook/Office.qlgenerator (46)
  com.apple.iwork.pages.pages -> /System/Library/QuickLook/iWork.qlgenerator (225)
  org.smpte.mxf -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.iwork.keynote.kth -> /System/Library/QuickLook/iWork.qlgenerator (225)
  org.openxmlformats.wordprocessingml.template -> /System/Library/QuickLook/Office.qlgenerator (46)
  cx.c3.compress-tar-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  io.iina.dv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.xesc -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.massanti.mediainfomac.mpeg2ts -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.protected-mpeg-4-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.internet-location -> /System/Library/QuickLook/Clippings.qlgenerator (950.2)
  io.iina.asf -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.divx.divx -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.gnu.gnu-zip-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  com.massanti.mediainfomac.nuppelvideo -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.sogou.pinyin.ssf -> /Library/QuickLook/SogouSkinFileQuickLook.qlgenerator (1.1)
  io.iina.ogg-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.iwork.numbers.numbers -> /System/Library/QuickLook/iWork.qlgenerator (225)
  org.videolan.wtv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.xmind.openformat.xmap -> /Applications/XMind.app/Contents/Library/QuickLook/XMindQuickLook.qlgenerator (1.0)
  com.apple.ical.ics -> /System/Library/QuickLook/iCal.qlgenerator (950.2)
  org.openxmlformats.presentationml.template.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (46)
  org.videolan.3gp -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.z-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  indy.jt.niceplayer.mkv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.dv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.image -> /System/Library/QuickLook/Image.qlgenerator (950.2)
  com.blurayplayersoftware.nuppelvideo -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.iina.quicktime -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.tar-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  io.iina.webm -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.tv.movpkg -> /System/Library/QuickLook/Movie.qlgenerator (950.2)
  org.openxmlformats.presentationml.slideshow.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (46)
  com.apple.iwork.numbers.template -> /System/Library/QuickLook/iWork.qlgenerator (225)
  com.microsoft.word.doc -> /System/Library/QuickLook/Office.qlgenerator (46)
  com.apple.ical.ics.todo -> /System/Library/QuickLook/iCal.qlgenerator (950.2)
  com.apple.safari.bookmark -> /System/Library/QuickLook/Bookmark.qlgenerator (950.2)
  io.mpv.wma -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  indy.jt.niceplayer.divx -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.microsoft.powerpoint.ppt -> /System/Library/QuickLook/Office.qlgenerator (46)
  org.niltsh.mplayerx-ogg-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.microsoft.windows-media-wm -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.iina.wtv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.perian.divx -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.microsoft.advanced-systems-format -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.finder.pictclipping -> /System/Library/QuickLook/Clippings.qlgenerator (950.2)
  org.videolan.divx -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.iina.mpeg-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  public.font -> /System/Library/QuickLook/Font.qlgenerator (950.2)
  org.oasis-open.opendocument.text -> /System/Library/QuickLook/Text.qlgenerator (950.2)
  public.html -> /System/Library/QuickLook/Web.qlgenerator (950.2)
  org.openxmlformats.presentationml.presentation -> /System/Library/QuickLook/Office.qlgenerator (46)
  public.xml -> /System/Library/QuickLook/Text.qlgenerator (950.2)
  org.webmproject.webm -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.openxmlformats.spreadsheetml.sheet.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (46)
  com.massanti.mediainfomac.ogv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.openxmlformats.spreadsheetml.template.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (46)
  com.apple.bom-compressed-cpio -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  org.niltsh.mplayerx-matroska-video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.niltsh.mplayerx-rmvb -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.microsoft.windows-executable -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  com.apple.application -> /System/Library/QuickLook/StandardBundles.qlgenerator (950.2)
  com.blurayplayersoftware.ogv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.openxmlformats.presentationml.template -> /System/Library/QuickLook/Office.qlgenerator (46)
  com.microsoft.windows-media-wmp -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.rtfd -> /System/Library/QuickLook/Text.qlgenerator (950.2)
  io.mpv.xvid -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.microsoft.powerpoint.pps -> /System/Library/QuickLook/Office.qlgenerator (46)
  public.json -> /System/Library/QuickLook/Text.qlgenerator (950.2)
  org.mythtv.nuppelvideo -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.microsoft.excel.xls -> /System/Library/QuickLook/Office.qlgenerator (46)
  public.svg-image -> /System/Library/QuickLook/Web.qlgenerator (950.2)
  org.perian.matroska -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.adobe.flash.video -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.xar-archive -> /Applications/MacZip.app/Contents/Library/QuickLook/MacZipQL.qlgenerator (49)
  org.videolan.gxf -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.vro -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.macblurayplayer.matroska -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.openxmlformats.wordprocessingml.document.macroenabled -> /System/Library/QuickLook/Office.qlgenerator (46)
  com.real.realmedia -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.quicktime -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.macblurayplayer.divx -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.apple.finder.textclipping -> /System/Library/QuickLook/Clippings.qlgenerator (950.2)
  com.microsoft.word.dot -> /System/Library/QuickLook/Office.qlgenerator (46)
  com.apple.iwork.pages.template -> /System/Library/QuickLook/iWork.qlgenerator (225)
  com.blurayplayersoftware.matroska -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  org.videolan.webm -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.mpv.wmv -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.iina.divx -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  io.iina.3gpp -> /Library/QuickLook/Video.qlgenerator (1.9.4)
  com.macblurayplayer.ogv -> /Library/QuickLook/Video.qlgenerator (1.9.4)

yashiro@SKYRIM ~ % qlmanage -p /Users/yashiro/SKYRIM/TEMP/1.mkv 
Testing Quick Look preview with files:
	/Users/yashiro/SKYRIM/TEMP/1.mkv
2022-07-15 12:54:03.197 qlmanage[4936:43023] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x7e03, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2022-07-15 12:54:03.215 qlmanage[4936:43023] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x14b07, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.

**Comment by FezVrasta** [comment]
Having the same problem on M1 Max

```
❯ qlmanage -p /Users/federicozivolo/Movies/TEST.mkv
Testing Quick Look preview with files:
	/Users/federicozivolo/Movies/TEST.mkv
2022-08-29 12:27:29.628 qlmanage[37494:917293] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x7503, name = 'com.apple.coredrag'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2022-08-29 12:27:29.639 qlmanage[37494:917293] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xac07, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
2022-08-29 12:27:32.639 qlmanage[37494:917301] Persistent UI failed to open file file:///Users/federicozivolo/Library/Saved%20Application%20State/com.apple.quicklook.qlmanage.savedState/window_2.data: No such file or directory (2)
```

**Comment by YashiroKirara** [comment]
After I uninstall the app Infuse, it works all ok
