### ISSUE TITLE
macOS 12.6 MacBook Pro M1 Pro - video files in finder with blank icons

### ISSUE THREAD

**Issue by aroom** [Marginal/QLVideo#98]
MacBook Pro M1 Pro - macOS Monterey 12.6

After installing this via homebrew, I noticed that some of the video files (almost all that can't be opened via Quicktime) had a blank icon, instead of IINA's or VLC's.

I tried to:
- uninstall it via homebrew
- force quit the Finder
- force quit QuickLookUIService
- dump some apple.com file in home/Library/Preference
- rebuild Launch Service via Onyx
- this command : `System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user`
- reset qlmanage
- reinstall macOS via the option on reboot (no clean install)

before reinstalling macOS, I did a safe reboot and the icon were corrected to IINA's in the session. but after rebooting my Mac in "normal" mode, the icon change back to blank when I used QuickLook with space bar.

can anyone have a pointer on why or how to correct this?

**Comment by eirnym** [comment]
I honestly know nothing about what does it mean to use x86_64 plugin on M1. 

But I was able to build with minor fixes from #97.

**Comment by SonnTakuu** [comment]
If you using infuse? It works well, after I uninstall the infuse.

**Comment by Marginal** [comment]
Closing. Please use **Help** → **Report an Issue** in the app if you're still seeing this behaviour with [release 2.00](https://github.com/Marginal/QLVideo/releases/latest), as described [here](https://github.com/Marginal/QLVideo/wiki/Troubleshooting#to-report-an-issue).

**Comment by aroom** [comment]
this seems to be fixed in the 2.00 release. thanks all.
