### ISSUE TITLE
Is .weba (webm audio file) supported?

### ISSUE THREAD

**Issue by gkostov** [Marginal/QLVideo#99]
Hi,

.webm videos work just fine but files with just audio inside or with a .weba extension do not show or play anything. I had a look at the info.plist files in the repo and I got to believe that .webm is treated as a video file format so the plugin is attempting to display a thumbnail of the video with no audio.
So I was wondering if .weba is supported at all or could I do some configuration of the plugin to have .webm (with only audio) or preferably .weba files to play just like .mp3 files do?

Thanks a lot!

**Comment by Marginal** [comment]
This QuickLook extension only provides thumbnails and preview pictures - it doesn't (currently) play audio or video files. And for audio-only files there's nothing to view.
